buildkite/test-collector-ruby

lib/rspec/buildkite/analytics/uploader.rb

This PR prints information for users when:
- No API key was supplied
- Invalid API key supplied
- Unknown errors

Print messages for token auth scenarios

---

lib/rspec/buildkite/analytics/version.rb
rspec-buildkite-analytics.gemspec

This PR relaxes version constraint of ActiveSupport dependency and bumps gem version to v0.3.1.

Relax Active Support constraint and bump to v0.3.1

---

Gemfile.lock
lib/rspec/buildkite/analytics/ci.rb
lib/rspec/buildkite/analytics/version.rb
spec/analytics/ci_spec.rb

We currently require two ENVs `BUILDKITE` and `BUILDKITE_BUILD_ID` to make Runs work (that Jobs inside a Build will be filed under one Run). This PR changes to only require `BUILDKITE_BUILD_ID`.

Require one less env

---

Gemfile.lock
lib/rspec/buildkite/analytics/ci.rb
lib/rspec/buildkite/analytics/version.rb
spec/analytics/ci_spec.rb

This PR restores the original behaviour of the CI check by always passing "buildkite" as the CI key. It keeps the new behaviour of only requiring and checking for BUILDKITE_BUILD_ID.

Only use BUILDKITE_BUILD_ID but keep previous env behaviour

---

lib/rspec/buildkite/analytics/socket_connection.rb
spec/analytics/socket_connection_spec.rb

On occasion we're seeing the analytics gem hard fail (i.e. makes the tests fail) with `IndexError`. It's not great. Let's catch the error and trigger our reconnect flow. Alternate approach to #54. 
The thing I'm not sure about: if an `IndexError` is thrown in other parts of the application that includes this gem, will it get caught here???

Catch IndexError

---

Gemfile.lock
lib/rspec/buildkite/analytics.rb
lib/rspec/buildkite/analytics/ci.rb
lib/rspec/buildkite/analytics/reporter.rb
lib/rspec/buildkite/analytics/session.rb
lib/rspec/buildkite/analytics/socket_connection.rb
lib/rspec/buildkite/analytics/uploader.rb
lib/rspec/buildkite/analytics/version.rb
spec/analytics/ci_spec.rb
spec/analytics/session_spec.rb
spec/analytics/socket_connection_spec.rb

This PR introduces a debug mode to the collector, which creates a text file with debug information that is uploaded to the job as an artifact. This was done because we realised that it wasn't possible with Datadog to exhaustively log the requests going through the socket, and it made debugging errors difficult. Hence, saving the relevant info to a text file, and also [adding logging on Buildkite](https://github.com/buildkite/buildkite/pull/7365) so we can build a complete picture of what has/hasn't been received. 
I have added two new environment params, `BUILDKITE_ANALYTICS_DEBUG_ENABLED` and `BUILDKITE_ANALYTICS_DEBUG_FILEPATH` which configure the enabling of debug mode, and the filepath to save the artifact at. I created a custom lightweight Logger class to facilitate the logging, it …

Add debug mode

---

lib/rspec/buildkite/analytics/reporter.rb

I believe `DateTime.current` is an activesupport-ism.
This gem does depend on activesupport so in theory we could use `DateTime.current`, however when I was running v0.4.0 with my non-rails rspec project I was getting:
```ruby
NameError: uninitialized constant RSpec::Buildkite::Analytics::Reporter::DateTime
Did you mean?  DateAndTime
/.../rspec-buildkite-analytics/lib/rspec/buildkite/analytics/reporter.rb:36:in `dump_summary'
```
I think we could fix this by adding an explicit `require "datetime"` to the file. However if we're going to do that, we may as well stick to the stdlib and use plain `Time.now` when generating a timestamp.

Avoid activesupport when generating debugging timestamps

---

lib/rspec/buildkite/analytics.rb

I tried using the debugging feature added in 0.4.0, and got a file permissions exception:
```
$ BUILDKITE_ANALYTICS_DEBUG_ENABLED=true be rspec spec/integration_spec.rb:16
Run options: include {:locations=>{"./spec/integration_spec.rb"=>[16]}}
.
Finished in 6.03 seconds (files took 0.21893 seconds to load)
1 example, 0 failures
bundler: failed to load command: rspec (/home/jh/.rbenv/versions/2.7.2/bin/rspec)
Errno::EACCES: Permission denied @ rb_sysopen - /bk-analytics-2021-11-08-00:28:15-.log.gz
/.../rspec-buildkite-analytics/lib/rspec/buildkite/analytics/reporter.rb:40:in `initialize'
/.../rspec-buildkite-analytics/lib/rspec/buildkite/analytics/reporter.rb:40:in `open'
/.../rspec-buildkite-analytics/lib/rspec/buildkite/analytics/reporter.rb:40:in `dump_summary' …
```

Use the system tmpdir as a default location for debugging logs

---

lib/rspec/buildkite/analytics/session.rb
lib/rspec/buildkite/analytics/socket_connection.rb
lib/rspec/buildkite/analytics/tracer.rb
lib/rspec/buildkite/analytics/uploader.rb
spec/analytics/session_spec.rb

I've added another thread to this gem but I swear it hasn't gotten more complicated 🙈
The major change here is that there's a new send queue for outbound messages. When an rspec test is finished, the results from that test are pushed into the send queue, rather than being written to the socket immediately. Instead, a new `write_thread` is instantiated that waits for messages to appear on the send queue, and sends them through the socket. This change means that reading and writing from the socket happen entirely in the two background threads, so any failures in them don't affect the main thread which is running the rspec tests. If the socket connection is broken for any reason, the existing reconnection + retransmission logic handles this. 
When the rspec tests have finished, our existing …

Move send to background thread

---

lib/rspec/buildkite/analytics/uploader.rb

Suppress this warning when not running on CI. Won't work for non-Buildkite builds but 🤷‍♀️

Do not print message in dev

---

lib/rspec/buildkite/analytics/reporter.rb
lib/rspec/buildkite/analytics/uploader.rb

This PR adds support for sending through two new pieces of data `failure_reason` and `failure_expanded`. There was a previous key called `failure_message` that I've removed as we never did anything with it. The content of this key was pretty much what is in `failure_reason`. 
`failure_reason` is a one line summary of the failure, e.g. `"Failure/Error: expect(true).to eq false"`. `failure_expanded` is an array, with each element being an array of `message_lines` and `backtrace` so that these elements can be formatted separately in the front end. 
I wasn't sure if it was worth adding a test for this without basically mocking out all of RSpec so I didn't 🤷‍♀️ I tested this with the three types of exception we'd expect, there's ones for failed expectation, multiple failed expectations and …

Send failure reasons for failed executions

---

lib/rspec/buildkite/analytics/reporter.rb
lib/rspec/buildkite/analytics/version.rb

In [the build](https://buildkite.com/buildkite/buildkite/builds/39934#87993c00-af14-4992-bdf3-2b766de430dc) for my [gem bump PR](https://github.com/buildkite/buildkite/pull/7621) there was a failing test so I thought "oh great I can test the new API", and then I realised that Capybara output is formatted differently 🤦‍♀️ 
And then I also found a new type of multiple error exception while testing this change lol

Even better failure reasons

---

lib/rspec/buildkite/analytics/uploader.rb

An early return to avoid calling methods on no response code paths.

Handle scenario when we got no response

---

lib/rspec/buildkite/analytics/session.rb

Enough customers reported seeing the "Timeout: waited 30s for welcome" error during the initial connection process that I thought it'd be good to put retries around this, like we do in the disconnect. 
My first thought was to refactor the reconnection code to be shared, but realised that this wasn't going to work as the reconnection code needs a mutex around reconnection attempts because we're not sure which thread will be doing the reconnection. Instead, I refactored the `connect` method to remove the instantiation of the write thread, so the `connect` now is just doing the ActionCable handshake business. This also means that we don't need to worry about locking in the initial connection phase, as the write thread doesn't exists yet, and we have a smaller set of errors that we expect …

Add retries to initial connection

---

Gemfile.lock
lib/rspec/buildkite/analytics/ci.rb
lib/rspec/buildkite/analytics/version.rb
spec/analytics/ci_spec.rb

We talked vaguely in the planning meeting about storing the collector version in the upload jsons S3 file but I thought that 
maybe it was easier/more efficient to just put it in the run env? Store it once per run rather than once upload part? It's also less code changes this way 😂

Store collector version

---

lib/rspec/buildkite/analytics.rb

This PR adds support for basic annotations. Annotations a special kind of span that will be supported by Test Analytics to facilitate easier debugging of threaded code within a test execution.
An annotation can be created by calling `RSpec::Buildkite::Analytics.annotate("some kind of annotation string")`
It'll then show as something like this in the UI.
.

Add support for annotation spans

---

lib/rspec/buildkite/analytics/ci.rb
spec/analytics/ci_spec.rb

This PR reinstates the support for GitHub Actions and CircleCI. It also adds support for override environment variables in the `BUILDKITE_ANALYTICS_` namespace.
If `GITHUB_RUN_NUMBER` is set then we will apply some sensible defaults for the run env based on those provided by GitHub Actions. If `CIRCLE_BUILD_NUM` is set we do the same for CircleCI. When the generic `CI` environment variable is set the run env "ci" is set to "generic".
When a URL and NUMBER are provided a link to the build will show in the Test Analytics UI regardless of CI platform. This also applies when the `CI` env is not set but `BUILDKITE_ANALYTICS_URL` and `BUILDKITE_ANALYTICS_NUMBER` are set.
`BUILDKITE_ANANLYTICS_MESSAGE` can be used within CI platforms that do not have an environment variable that is equivalent to …

Support multiple CI platforms and generic env

---

Gemfile.lock
rspec-buildkite-analytics.gemspec

The current constraint on ActiveSupport prevents using this gem with patch releases of ActiveSupport / Rails 7, e.g.
```
Bundler could not find compatible versions for gem "activesupport":
In Gemfile:
rails (= 7.0.2.3) was resolved to 7.0.2.3, which depends on
activesupport (= 7.0.2.3)
rspec-buildkite-analytics was resolved to 0.6.1, which depends on
activesupport (>= 5.2, <= 7.0)
```
This relaxes the constraint to permit them.

Relax Active Support constraint

---

lib/rspec/buildkite/analytics/uploader.rb
spec/analytics/uploader_spec.rb

In the `Session` class we convert our test results into a JSON string to
send over the wire. Calling `to_json` on a string that has invalid UTF-8
characters result in a `JSON::GeneratorError`. Which means that if a
test name, or any other data we generate has any invalid characters we
won't be able to send the results to analytics. So we replace any of
these characters.
I think it would have been good to avoid the recursive function here and
only re-encoded the strings that are generated from the users test
suite, but that happens in quite a few places, it would be easy to skip
doing this when adding additional data from the test suite as well; also
those values appearing in deep nested structures, so we can't just call
that function for a few keys, we need to recursively visit each …

Replace invalid UTF-8 characters in test names

---

CHANGELOG.md
Gemfile.lock
lib/rspec/buildkite/analytics/version.rb

Bump version to v0.8.0: [CHANGES](https://github.com/buildkite/rspec-buildkite-analytics/compare/v0.7.0...main).

Bump version to v0.8.0

---

lib/rspec/buildkite/analytics/session.rb

During session close we send an EOT message that triggers a confirm response containing all idents accepted by the server. If, after confirmation, there are some idents remain unconfirmed we now retransmit them, send another EOT and await their confirmation.
This fixes an issue where we would wait the full 75 second timeout if any idents remained unconfirmed.
To further improve issues with long timeouts, I have added three new environment variables:
- `BUILDKITE_ANALYTICS_CONFIRMATION_TIMEOUT` - seconds to wait for ident confirmation during session close
- `BUILDKITE_ANALYTICS_RECONNECTION_ATTEMPTS` - number of reconnection attempts if session is unexpectedly closed
- `BUILDKITE_ANALYTICS_RECONNECTION_WAIT` - seconds to wait between reconnection attempts
I've also added some status …

Retransmit unconfirmed idents

---

lib/rspec/buildkite/analytics/library_hooks/rspec.rb
lib/rspec/buildkite/analytics/reporter.rb
lib/rspec/buildkite/analytics/uploader.rb

Backport from #86.
`RSpec::Buildkite::Analytics.uploader.traces` was an array and we would loop through this many times to find our matching trace. On larger test suites with 1000s of tests, it would cause 100s of 1000s of loops. We can instead lookup the value directly with a hash.

Make trace lookup faster by using a hash

---

lib/buildkite/collector.rb
lib/buildkite/collector/logger.rb
lib/buildkite/collector/rspec_plugin/reporter.rb
lib/buildkite/collector/session.rb
lib/buildkite/collector/socket_connection.rb
lib/buildkite/collector/uploader.rb
spec/collector/logger_spec.rb
spec/collector/socket_connection_spec.rb

This Pull Request adds a `Logger` class to replace `puts`, `$stderr.puts` and custom `logger.write` usages, which replace #96 that if we want to suppress unwanted log messages, set the logger to send logs to `/dev/null`:
```ruby
RSpec::Buildkite::Analytics.logger = Logger.new("/dev/null")
```
- Introduce a Logger class which can be changed by user
- The logs can be enabled on by env `BUILDKITE_ANALYTICS_DEBUG_ENABLED` or standard Ruby flag `$DEBUG`
- default log level is `::Logger::WARN`
- The log has ISO 8601 timestamp with 9 digit precision, Process id and current Thread id
`2022-05-19T07:43:52.795221000Z pid=1977 tid=7840 DEBUG: starting socket connection process`
- Replace all `puts`, `$stderr.puts` with `RSpec::Buildkite::Analytics.logger.debug` — Should this be `INFO` instead 🤔? To …

Introduce Logger utility

---

lib/buildkite/collector/rspec_plugin/reporter.rb
spec/collector/logger_spec.rb
spec/collector/rspec_plugin/reporter_spec.rb
spec/support/io_helpers.rb
spec/support/rspec_example_trace_helpers.rb

The [reporter class](https://github.com/buildkite/rspec-buildkite-analytics/blob/f5636f04ba1c0ed1add2ef43d51a2216e5d15af7/lib/buildkite/collector/rspec_plugin/reporter.rb#L4) is under `RSpecPlugin`. Spotted when test failed:

Fix namespace of Reporter

---

lib/buildkite/collector/socket_connection.rb

We hit an `EOFError` that happens frequently, and before we could fix that, use `WARN` instead of `ERROR` to improve user experience using our collector.
The specific `EOFError` was:
```
EOFError: end of file reached
lib/ruby/3.0.0/openssl/buffering.rb:148:in `sysread'
lib/ruby/3.0.0/openssl/buffering.rb:148:in `readpartial'
rspec-buildkite-analytics/lib/buildkite/collector/socket_connection.rb:73:in `block in initialize'
```

Improve user experience running the collector

---

lib/buildkite/collector/session.rb
lib/buildkite/collector/socket_connection.rb

When the `disconnected` attempt exhausted, we re-raise the exception that bubbles up back to the socket connection. People may have installed the Ruby collector on an Android project, and in this case, we should fail gracefully.

Handle re-raised disconnected exceptions

---

lib/buildkite/test_collector.rb
lib/buildkite/test_collector/library_hooks/minitest.rb
lib/buildkite/test_collector/library_hooks/rspec.rb

Sometimes people might run into issues where the detailed tracing is incompatible with their tests or is causing tests to run slower. To make it so they can keep using Test Analytics I've added the option to disable the detailed tracing.
```ruby
Buildkite::TestCollector.configure(
...
tracing_enabled: false
)
```

Detailed tracing can be disabled

---

lib/buildkite/test_collector/minitest_plugin/trace.rb
spec/test_collector/minitest_plugin/trace_spec.rb

**Issue**
See #111, this lib seems to expect a string for the `project_dir`, but `Rails.root` returns `Pathname`
**Steps to reproduce**
Run minitest with the gem enabled in a Rails 6+ app
**Expected**
The gem should do its job and report analytics back to Buildkite
**Actual**
See #111 for the output
As suggested by @nickvanw, this PR simply calls `to_s` on `Rails.root` in the `project_dir` method in `minitest_plugin/trace.rb`
I added a test too that fails without the fix.

Fix `project_dir` issue expecting a string, not a `Pathname`

---

lib/buildkite/test_collector/minitest_plugin/trace.rb
lib/buildkite/test_collector/uploader.rb

Remove these warnings from the gem for Minitest:
```
/Users/hhh/dev/test-collector-ruby/lib/buildkite/test_collector/minitest_plugin/trace.rb:75: warning: method redefined; discarding old failure_reason
/Users/hhh/dev/test-collector-ruby/lib/buildkite/test_collector/minitest_plugin/trace.rb:79: warning: method redefined; discarding old failure_expanded
```
And remove a warning from `Uploader`:
```
/Users/hhh/dev/test-collector-ruby/lib/buildkite/test_collector/uploader.rb:59: warning: assigned but unused variable - request_id
```

Remove warnings 

---

lib/buildkite/test_collector.rb

Thanks to @pda pointed out in https://github.com/buildkite/test-collector-ruby/pull/97#issuecomment-1147098900.
Remove unused `debug_filepath`.
This was introduced at https://github.com/buildkite/test-collector-ruby/commit/8d99faf74dbf505476202c2ab67e5a0cdd493c76 to dump debug logs into a preferred location but it is not in used anymore
I do not believe anyone but us uses this feature but this is a breaking API change for the `configure` method.

Remove unused debug_filepath

---

lib/rspec/buildkite/analytics.rb
lib/rspec/buildkite/analytics/version.rb
rspec-buildkite-analytics.gemspec

This merges to v0.8.1 (7082e50).
This PR adds deprecation notice to the old gem description, post install messages and warning when using it.

Releave v0.8.2 of rspec-buildkite-analytics with deprecation messages

---

lib/buildkite/test_collector/library_hooks/minitest.rb

It has been renamed to `Minitest` since 2013 (but `MiniTest` still kept as an alias) but for the love of our pinkies...
[![CleanShot 2022-06-09 at 12 47 34@2x](https://user-images.githubusercontent.com/1000669/172760051-d2bfd6ea-e58a-45f0-a3c7-2d23a0907752.png)](https://github.com/minitest/minitest/blob/master/History.rdoc#500--2013-05-10-)

Use new Minitest spelling

---

lib/minitest/buildkite_collector_plugin.rb
spec/test_collector/minitest_plugin/without_plugin_spec.rb

**Issue**
Requiring the gem but not running `Buildkite::TestCollector.configure(hook: :minitest)` causes an exception:
**Steps to reproduce**
- In a Rails 7 app
- Add `buildkite-test_collector` to the `Gemfile`
- Do not add ```Buildkite::TestCollector.configure(hook: :minitest)```
**Expected**
Tests should run fine as though the test collector gem wasn't installed
**Actual**
- If `require "buildkite/test_collector"` is present, but `Buildkite::TestCollector.configure(hook: :minitest)` is not, we get `uninitialized constant Buildkite::TestCollector::MinitestPlugin`
- If neither of the above are present, but the gem is in the Gemfile, we get: `uninitialized constant Minitest::Buildkite`
**Fix**
This just adds an additional constant check in the `Minitest` plugin, and also adds a test to …

Loading minitest without initializing the plugin should work

---

lib/buildkite/test_collector.rb

Resolves https://github.com/buildkite/test-collector-ruby/issues/122
Ruby 2.5 removed support for multiline headers
https://github.com/ruby/ruby/commit/0078e40115fd53e2cafd4e8cfb6ff5fd7f87c3db
There shouldn't be any new line characters, carriage returns or similar
characters in the BUILDKITE_ANALYTICS_TOKEN environment variable. So we
should remove any instances of leading or trailing whitespace characters
from the token to avoid the error raised in Ruby net/http.
Internal reference:
PIE-927

Remove whitespace characters from ANALYTICS_TOKEN to avoid multi-line headers

---

lib/buildkite/test_collector/ci.rb
spec/test_collector/ci_spec.rb

This will be displayed before and after the name of a Run respectively.
- Prefix: `BUILDKITE_ANALYTICS_RUN_NAME_PREFIX`
- Suffix: `BUILDKITE_ANALYTICS_RUN_NAME_SUFFIX`

Allow specifying run name prefix and suffix

---

lib/buildkite/test_collector/minitest_plugin.rb

This should fix #131, where I described the problem in details.

Use `after_teardown` instead of `before_teardown` in MiniTest

---

lib/buildkite/test_collector/tracer.rb

Avoid breaking test suite that stubs `Process.clock_gettime` by replacing calling `Concurrent.monotonic_time` with a custom `MonotonicTime.call`. 
The fix was suggested by @ChrisBR at https://github.com/buildkite/test-collector-ruby/issues/131#issuecomment-1168343196 (thanks!)

Use the private reference trick to get time instead

---

lib/buildkite/test_collector/ci.rb
spec/test_collector/ci_spec.rb

Resolves https://github.com/buildkite/test-collector-ruby/issues/135
We are using the environment GITHUB_REF which includes the prefix
ref/branch which isn't what we want. GITHUB_REF_NAME returns the
branch/tag without the prefix.
GITHUB_REF returns
* refs/heads/main
* refs/pulls/2000/merge
GITHUB_REF_NAME returns
* main
* my-branch-name
Reference https://docs.github.com/en/actions/learn-github-actions/environment-variables

Remove branch reference prefix in Github Actions

---

lib/buildkite/test_collector.rb
lib/buildkite/test_collector/ci.rb
lib/buildkite/test_collector/error.rb
lib/buildkite/test_collector/library_hooks/minitest.rb
lib/buildkite/test_collector/library_hooks/rspec.rb
lib/buildkite/test_collector/logger.rb
lib/buildkite/test_collector/minitest_plugin.rb
lib/buildkite/test_collector/minitest_plugin/trace.rb
lib/buildkite/test_collector/rspec_plugin/reporter.rb
lib/buildkite/test_collector/rspec_plugin/trace.rb
lib/buildkite/test_collector/session.rb
lib/buildkite/test_collector/socket_connection.rb
lib/buildkite/test_collector/tracer.rb
lib/buildkite/test_collector/uploader.rb
lib/minitest/buildkite_collector_plugin.rb
spec/test_collector/ci_spec.rb
spec/test_collector/logger_spec.rb
spec/test_collector/minitest_plugin/reporter_spec.rb
spec/test_collector/rspec_plugin/reporter_spec.rb
spec/test_collector/session_spec.rb
spec/test_collector/socket_connection_spec.rb

This Pull Request explicitly doing all `require` in the entry point `test_collector.rb`.
For Minitest plugin (file named with `_plugin` suffix) in non-web app, we cant be sure our Collector is `require`’d before Minitest finds the plugin, so need to `require` tracer.

Make ruby collector work better for non-web app

---

README.md

Copied this to an existing project that runs Rubocop during pre-commit hook and it complained that we shouldn't use double quotes when they aren't needed

Avoid linters complaining about double quotes

---

lib/buildkite/test_collector/ci.rb
spec/test_collector/ci_spec.rb

This reverts buildkite/test-collector-ruby#130 which we discussed on Basecamp.

Revert "Allow specifying run name prefix and suffix"

---

lib/buildkite/test_collector.rb
lib/buildkite/test_collector/library_hooks/minitest.rb
lib/buildkite/test_collector/library_hooks/rspec.rb
spec/test_collector_spec.rb

It's important the collector does not raise exceptions and cause test
suites to fail. Some customers have seen exceptions raised when
connecting to Buildkite (not a surprise as networks are complicated and
unreliable).
This PR modifies the connection process to catch all StandardErrors and
log them. Trace data will be lost; however, the customer's build will
not fail which is more important.
We also intend to address the underlying issues; however, this PR is an
important defensive measure to protect customer builds.

Suppress errors when connecting to Buildkite

---

lib/buildkite/test_collector/socket_connection.rb

PIE-983
When an EOFError exception is raised, we want log at the 'error' level.
This is also consistent with other exceptions that are rescued.
Resolves #141

Fix logging level from debug to error

---

lib/buildkite/test_collector/session.rb
spec/test_collector/session_spec.rb

PIE-979
It is possible for test suites to mock the parse method of JSON.
For example:
allow(JSON).to receive(:parse).and_raise(JSON::ParserError)
This will cause the test collector library to misbehave.
We can resolve this problem by updating the test collector code to
use a private reference to the JSON method which is immune to mocking.
This solution is similar to
https://github.com/buildkite/test-collector-ruby/pull/132
and https://github.com/ruby/timeout/pull/18/files
Resolves https://github.com/buildkite/test-collector-ruby/issues/144

Use a private reference to JSON.parse to prevent it being mocked 

---

lib/buildkite/test_collector/ci.rb
spec/test_collector/ci_spec.rb

This will be displayed before and after the name of an Execution respectively
implements PIE-964

Allow specifying execution name prefix / suffix

---

CHANGELOG.md
Gemfile.lock
lib/buildkite/test_collector/version.rb

All changes: https://github.com/buildkite/test-collector-ruby/compare/v1.1.3...2724f0d8196c2f9b0c821184cdf7ec3ca784805c
This PR releases v1.2.3, bump minor version because it introduced a new feature: [Allow specifying execution name prefix / suffix](https://github.com/buildkite/test-collector-ruby/pull/140).
PIE-1028

Release v1.2.3

---

CHANGELOG.md
Gemfile.lock
lib/buildkite/test_collector/version.rb

All changes: https://github.com/buildkite/test-collector-ruby/compare/v1.2.3...d41ee84e
This PR releases v1.2.4, bump minor version because it is a bug fix: [Fix instrumentation of sleep does not support sleeping forever #153](https://github.com/buildkite/test-collector-ruby/pull/153).
PIE-1189

Release v1.2.4

---

buildkite-test_collector.gemspec

Changes the minimum supported ActiveSupport version to allow the gem to be used with Rails 4.2 applications. This can be helpful for those using RailsLTS to receive backported security fixes to older versions of Rails.

Allow earlier Rails versions

---

CHANGELOG.md
Gemfile.lock
lib/buildkite/test_collector/version.rb

All changes: https://github.com/buildkite/test-collector-ruby/compare/v1.2.4...64566d59
This PR releases v1.2.5: [allow collector to use in earlier rails version #155](https://github.com/buildkite/test-collector-ruby/pull/155).

Release v1.2.5

---

.gitignore
lib/buildkite/test_collector.rb
lib/buildkite/test_collector/ci.rb
spec/test_collector/ci_spec.rb
spec/test_collector_spec.rb

As we experiment with new TA features we need a way to send through experimental environment variables. Rather than building against experimental TA branches we can send the custom env using config in our `spec_helper.rb`
Specify custom env with:
```
Buildkite::TestCollector.configure(hook: :rspec, env: { ... })
```

Add ability to pass custom run env to TA API

---

lib/buildkite/test_collector/minitest_plugin/reporter.rb

This problem was introduced in  2eb068dda0a7cf00fdaa644d3204462b5588f2ad.
In our test pipeline, we include the `test-collector-ruby` gem in our `:test` Gemfile group but only configure it to run on certain builds. So we have code like this:
```rb
group :test do
gem "buildkite-test_collector", "~> 1.2.5", require: false
end
```
```rb
if !!ENV["BUILDKITE_ANALYTICS_ENABLED"]
require "buildkite/test_collector"
Buildkite::TestCollector.configure(hook: :minitest)
end
```
If `BUILDKITE_ANALYTICS_ENABLED` is not set then we never call `configure` and this piece of code is never run:
```rb
Buildkite::TestCollector.uploader = Buildkite::TestCollector::Uploader
```
So `Buildkite::TestCollector.uploader` is nil and this code falls over:
```rb
if trace = …
```

Cope with the gem being loaded but not configured when using minitest

---

lib/buildkite/test_collector.rb
lib/buildkite/test_collector/library_hooks/rspec.rb

This PR adds the functionality to create a gzipped json file that contains the traces for an rspec test suite. The file is saved to a location specified by a new config param. Perhaps this could also become an environment variable later, but this is just a first cut of this idea, and mostly used for testing. 
It shouldn't affect any current functionality of the gem, as the param defaults to nil. 
This functionality is added in support of testing [PR #10671](https://github.com/buildkite/buildkite/pull/10671), which adds the ability to ingest test results for analytics from an artifact. This creates the artifact for testing purposes. I haven't added any tests, or looked into minitest support for this reason. 
I tried this out locally and verified that the appropriate file was created 
Will …

Add ability to write test results to a file

---

CHANGELOG.md
Gemfile.lock
README.md
lib/buildkite/test_collector/ci.rb
lib/buildkite/test_collector/version.rb
spec/test_collector/ci_spec.rb

This PR tweaks the collector name passed to the Analytics::API so that we can collect accurate information about which collectors are in use by our customers. It is linked to this [piece of work in linear](https://linear.app/buildkite/issue/PIE-435/store-collector-type-junit-rspec-etc).
This PR also adds instructions for deploying this collector, which is consistent with our other test-collectors.
[PIE-1365](https://linear.app/buildkite/issue/PIE-1365/update-ruby-collector-name-to-be-consistent-with-other-collectors)

[PIE-1365] Update ruby collector API payload

---

lib/buildkite/test_collector/minitest_plugin/trace.rb
spec/test_collector/minitest_plugin/trace_spec.rb

There is a bug in minitest collector that causes failure_expanded not to be sent to Test Analytics. (see implementation)
minitest is sending a long failure message as failure_reason.
see an example from my local test:
```
RuntimeError: bang!!! 💥
/Users/naufanrizal/Repositories/minitest-example/test/minitest/test_example.rb:19:in `explode'
/Users/naufanrizal/Repositories/minitest-example/test/minitest/test_example.rb:8:in `block (2 levels) in <top (required)>'
```
We want to limit the length of `failure_reason` that can be stored by Test Analytics in the upcoming changes. Therefore, we need to split the failure messages into a short summary that goes into `failure_reason` and the detail that goes into `failure_expanded`
1. send the first line of failure message as `failure_reason`
2. send …

[PIE-1387] Send `failure_expanded` from minitest

---

lib/buildkite/test_collector/socket_connection.rb

[kivikakk](https://github.com/kivikakk) pointed on that they have been observing lots of `EOF` errors and that logging with a 'warn' is more appropriate than 'error'. https://github.com/buildkite/test-collector-ruby/pull/147#issuecomment-1250485611
Their team has currently forked this Collector as a workaround and it would be great if they don't have to maintain their own fork.
`OpenSSL::SSL::SSLError` is raised when using OpenSSL 3 so catching this and handling it the same way as EOF errors are hadnled seems appropriate.
`OpenSSL::SSL::SSLError` is quite a broad exception class (and Ruby's OpenSSL implementation only exposes the error [through the message](https://github.com/ruby/openssl/blob/173be6690589120976bd3f8e55eea13eae6aed46/ext/openssl/ossl.c#L268-L310), so the best we could do …

Only warn on EOF errors and also catch SSLErrors

---

lib/buildkite/test_collector/minitest_plugin/trace.rb
lib/buildkite/test_collector/rspec_plugin/trace.rb
spec/test_collector/rspec_plugin/trace_spec.rb

We no longer using identifier in TA and have stopped saving the value in our database. This PR removes identifier from Rspec trace and Minitest trace. We are not going to make a release for this small change.
Ticket: https://linear.app/buildkite/issue/PIE-1478/remove-identifier-from-ruby-test-collector 
Parent ticket: https://linear.app/buildkite/issue/PIE-1427/remove-identifier-from-test-collector-payloads
To verify the change, Rose and I paired together to do an integration test for Rspec.I updated the gemfile on my local buildkite repo to use the local test-collector-ruby gem
- Running rspec test at local not causing any errors
- Records are created in the database, and we can see the runs and executions from the UI
- `identifier` is not included in the S3 file
To verify the changes to …

PIE-1478/Remove identifier from trace

---

lib/buildkite/test_collector.rb
lib/buildkite/test_collector/socket_connection.rb
lib/buildkite/test_collector/socket_session.rb
lib/buildkite/test_collector/uploader.rb
spec/test_collector/socket_connection_spec.rb
spec/test_collector/socket_session_spec.rb

This PR is just a precursor to #174, which switches test-collector-ruby to send upload data via the Upload API rather than the ActionCable websocket for RSpec test suites. 
This PR renames the previous `Session` to `SocketSession` as Minitest is still using the websocket implementation. As PR #174 creates a new `Session` object, the rename was pulled out into a separate PR for clarity of reading PR #174

Rename session to socket session

---

lib/buildkite/test_collector.rb
lib/buildkite/test_collector/http_client.rb
lib/buildkite/test_collector/library_hooks/rspec.rb
lib/buildkite/test_collector/rspec_plugin/reporter.rb
lib/buildkite/test_collector/session.rb
lib/buildkite/test_collector/uploader.rb
spec/test_collector/http_client_spec.rb
spec/test_collector/session_spec.rb

This is the first part of [PIE-1436](https://linear.app/buildkite/issue/PIE-1436/drop-support-for-actioncableuploadchannel-from-the-ruby-collector), which will drop ActionCable support from test-collector-ruby. This removes ActionCable support for test suites configured to use RSpec. 
Use of the SocketSession (websocket implementation) is removed from the RSpec config and replaced with a new Session that sends requests in batches via the Upload API. The batch size is configured via a new env variable, `BUILDKITE_ANALYTICS_UPLOAD_BATCH_SIZE`, which defaults to 500. This is configurable mainly to allow ease of testing. 
The implementation of this leverages RSpec [custom formatters](https://rspec.info/documentation/3.9/rspec-core/RSpec/Core/Formatters.html). After every test, we have defined …

Batch Upload API requests for rspec

---

CHANGELOG.md
Gemfile.lock
lib/buildkite/test_collector/version.rb
spec/test_collector/http_client_spec.rb

Creating a pre-release for the major changes to the Rspec plugin 
Have given it another integration test locally by running `BUILDKITE_ANALYTICS_RSPEC_TOKEN=xx-local-analytics-key BUILDKITE_ANALYTICS_UPLOAD_BATCH_SIZE=2 BUILDKITE_BUILD_ID="hi" rspec spec/models/admin/goto_spec.rb` and verified that all relevant records and S3 files are created.

[PIE-1436] Pre-release Rspec changes

---

lib/buildkite/test_collector/library_hooks/minitest.rb
lib/buildkite/test_collector/minitest_plugin/reporter.rb

This changes the minitest plugin to use to the Upload API rather than the ActionCable websocket to send test data. 
I used the minitest setup in this branch: https://github.com/buildkite/buildkite/pull/11383 and I ran these two tests:
`BUILDKITE_ANALYTICS_RSPEC_TOKEN=local bin/rails test test/test.rb`
`BUILDKITE_ANALYTICS_RSPEC_TOKEN=local BUILDKITE_ANALYTICS_UPLOAD_BATCH_SIZE=1 bin/rails test test/test.rb`
And everything works as expected, and the right models and S3 files are created. I am fairly confident that this change is fine despite only testing against a small dummy test suite, I thought about finding a minitest customer to get them to try this change out but I'm not sure that's really worth the effort. 
I am not planning on doing a release just for this change, will follow up …

Switch minitest to upload api

---

DESIGN.md
Gemfile.lock
buildkite-test_collector.gemspec
lib/buildkite/test_collector.rb
lib/buildkite/test_collector/http_client.rb

Getting rid of some stale requirements and references to websockets before general release of v2.X of gem

Remove remaning "websocket" references

---

buildkite.yaml
lib/buildkite/test_collector/http_client.rb
spec/test_collector/http_client_spec.rb

Gzip the payload for Upload API requests, and set Content-Encoding header so the server knows how to decode the payload. Relevant changes to bk/bk to support this is in [PR #12006](https://github.com/buildkite/buildkite/pull/12006)

Gzip body of upload request

---

lib/buildkite/test_collector/minitest_plugin/reporter.rb

I'm not entirely sure about this fix but we still get an error if we don't initialize the plugin locally.
Potentially related to https://github.com/buildkite/test-collector-ruby/pull/125.

Fix nil pointer

---

lib/buildkite/test_collector/uploader.rb

Rescuing network connection errors are much too whack-a-mole for my liking so I'm going to add the specific one raised in Issue #190 to the retryable list, but then also rescue from StandardError (like we did with the websocket implementation) so any further issues in the future don't bubble up and cause builds to fail.

Rescue standard error

---

lib/buildkite/test_collector.rb
lib/buildkite/test_collector/ci.rb
lib/buildkite/test_collector/library_hooks/rspec.rb
lib/buildkite/test_collector/minitest_plugin/trace.rb
lib/buildkite/test_collector/rspec_plugin/trace.rb
lib/buildkite/test_collector/uuid.rb
spec/test_collector/ci_spec.rb
spec/test_collector/http_client_spec.rb

Builds upon #189 and #187 
We've decided to stop generating execution IDs client side. However, that wasn't the only place the ruby test collector was using SecureRandom.uuid, so am also still including the patch that @ChrisBr submitted that @blaknite then added to 
Has been integration test against bk/bk
There'll be a follow up PR on bk/bk that also ignores any execution IDs that are sent from test collector clients but this PR can be merged and released independently of that

Stop sending execution id

---

README.md
lib/buildkite/test_collector/uploader.rb

We rescue a standard error during upload to prevent builds from failing. However, there is no way to know what the real errors are. We want to log the error while silently rescuing it so we know what went wrong.
This fixes issue https://github.com/buildkite/test-collector-ruby/issues/194
I also updated the documentation for an extra step when using VCR in a test suites, as raised by that same issue.

Log standard error raised during upload

---

CHANGELOG.md
Gemfile.lock
lib/buildkite/test_collector/version.rb

What's changed:
- [Log standard error raised during upload](https://github.com/buildkite/test-collector-ruby/pull/195)

Bump version to v2.3.1

---

buildkite.yaml

Update build pipeline to run tests under multiple Ruby versions
All minor Ruby versions from 3.2 to 2.3 will be tested.
The gemspec says Ruby versions from 2.3.x are supported, however
some modern Ruby syntax was introduced which breaks compatibility
for older Ruby versions.

Test gem under every supported Ruby version

---

buildkite.yaml
lib/buildkite/test_collector/ci.rb
lib/buildkite/test_collector/minitest_plugin/trace.rb
lib/buildkite/test_collector/rspec_plugin/trace.rb

The gemspec file states Ruby versions 2.3 and above is supported but there is code which breaks compatibility with versions 2.3, 2.4 and 2.5.
See https://github.com/buildkite/test-collector-ruby/issues/199
This PR removes the use Ruby features/syntax that were introduced in 2.4, 2.5 and 2.6.

Restore compatibility with older Ruby versions

---

buildkite.yaml

Test collector on 3.3-rc Ruby in anticipation of Dec 2023 release
Failures on 3.3-rc will not fail the build.

Test collector on 3.3-rc Ruby in anticipation of Dec 2023 release

---

CHANGELOG.md
Gemfile.lock
lib/buildkite/test_collector/version.rb

Relevant changes 
- Add support for Codeship #198 - @swebb
- Restore compatibility with older Ruby versions #201 - @gchan
- Report Ruby version to Test Analytics #203 - @gchan

Prepare gem for 2.3.2 release

---

CHANGELOG.md
Gemfile.lock
lib/buildkite/test_collector/version.rb

What's changed:
- [Output a summary of TA links in rspec log](https://github.com/buildkite/test-collector-ruby/pull/207) 
- [Add signifier to link outputs](https://github.com/buildkite/test-collector-ruby/pull/209)

Bump version to 2.4.0

---

Gemfile.lock
buildkite-test_collector.gemspec
lib/buildkite/test_collector.rb
lib/buildkite/test_collector/minitest_plugin/trace.rb
lib/buildkite/test_collector/rspec_plugin/reporter.rb
lib/buildkite/test_collector/rspec_plugin/trace.rb
lib/buildkite/test_collector/test_links_plugin/formatter.rb
lib/buildkite/test_collector/tracer.rb
spec/spec_helper.rb

Hi fine Bikkies 👋🏻
I just went to add the test collector to a Hanami app, and noticed it was bringing along ActiveSupport as a dependency. I don't have that gem within my app, have a self-imposed challenge to keep it that way, and thought I'd investigate whether it's actually required here. I don't think it is?
There are three uses I've found and adjusted (in separate commits below):
* The `blank?`/`present?` convenience methods - which yes, are convenient, but also easily changed to pure Ruby options.
* `Hash#with_indifferent_access` - as far as I could see within the code, the hashes are created with symbol keys and strings aren't being used to refer to the keys at later points. The tests are also fine with this being removed, so, I hope this is fine!
* `ActiveSupport::Notifications` - …

Remove ActiveSupport from being a primary dependency.

---

lib/buildkite/test_collector.rb
lib/buildkite/test_collector/ci.rb
lib/buildkite/test_collector/library_hooks/rspec.rb
lib/buildkite/test_collector/minitest_plugin.rb
lib/buildkite/test_collector/tracer.rb
spec/test_collector/ci_spec.rb
spec/test_collector/minitest_plugin/trace_spec.rb
spec/test_collector/tracer_spec.rb
spec/test_collector_spec.rb

Introduce the ability to filter trace spans by a minimum duration, so that fast spans can be discarded and only slow (interesting) spans are kept in memory and uploaded.
Configurable using `BUILDKITE_ANALYTICS_TRACE_MIN_SECONDS` (decimal value) in environment.

Trace spans can be filtered by a minimum duration

---

buildkite.yaml

We're starting to test a new queue, and I'm looking for projects to experiment with. These new agents are quite different, but have docker and bash so I expect things should Just Work.
If there's any surprises, we can safely revert.
The new agents aren't authenticated to ECR, so I've switched to loading ruby docker images from the public ECR gallery. That's our preferred style these days anyway - agents that are authenticated to ECR will transparently use ECR as a cache. We don't need to explicitly use ECR images.

Run tests on a new queue

---

buildkite.yaml

Ruby 3.3 has been released so we don't need to run the tests against the
RC version of Ruby. I've removed the RC step completely, but it can
be reintroduced if we want to test against the next RC in the future.
I've also added 3.3 to the standard build matrix.

Update CI pipeline to reflect Ruby 3.3 has been released

---

lib/buildkite/test_collector/http_client.rb
lib/buildkite/test_collector/uploader.rb
spec/test_collector/http_client_spec.rb
spec/test_collector/uploader_spec.rb

part of PIE-2813
Fix uploader so it will throw a runtime error if backend does not return 2xx. 
This will result in a log message if any upload fails.
Note it will not fail a build if the upload fails.

Handle http response errors during upoad.

---

lib/buildkite/test_collector.rb
lib/buildkite/test_collector/tracer.rb
spec/test_collector/tracer_spec.rb

When using the collector, sometimes there can many uninteresting spans in the trace from things like selenium or other framework noise. This adds a seam to allow users to have control of filtering out uninteresting trace spans.
```rb
ignore_selenium_requests = ->(span) do
return true unless span[:section] == "http"
!span.dig(:detail, :url) =~ /^http://selenium:4444//
end
Buildkite::TestCollector.configure(hook: :rspec)
Buildkite::TestCollector.span_filters << ignore_selenium_requests
```
This doesn't need to be a lambda, any `#call`-able will work, as long as it returns a truthy value from the callback when we want to retain the span.
Multiple `span_filters` can be provided, and as long they _all_ return a truthy value, then the span will be retained, this allows composing multiple …

Add configurable span filters.

---

README.md
buildkite-test_collector.gemspec
lib/buildkite/test_collector/test_links_plugin/formatter.rb
spec/test_collector/test_links/formatter_spec.rb

With the recent relaunch and rebranding of Test Engine, this PR updates all references within the collector from "Test Analytics" to "Test Engine."

Update references from Test Analytics to Test Engine

---

lib/buildkite/test_collector/library_hooks/rspec.rb
spec/spec_helper.rb

This formatter was removed in
https://github.com/buildkite/test-collector-ruby/pull/228 but this reference was accidentally left behind.

Remove call to deleted formatter

---

lib/buildkite/test_collector/http_client.rb
lib/buildkite/test_collector/uploader.rb
spec/test_collector/http_client_spec.rb

Summary:
- rename `contact` to `request` (and `contact_uri` to `endpoint_uri`)
- take `api_token` as an arg, rather than reaching into global config
I'm extracting this refactor from another change which will add tagging support, to make that other change smaller.

HTTPClient: minor refactor; naming, constructor args

---

lib/buildkite/test_collector/http_client.rb
lib/buildkite/test_collector/uploader.rb
spec/test_collector/http_client_spec.rb
spec/test_collector/session_spec.rb
spec/test_collector/uploader_spec.rb

Further to #233, refactor `HTTPClient#post_upload` (previously called `#post_json`) to receive `run_env` as a keyword argument, instead of reaching out to `Buildkite::TestCollector::CI.env` (which is then dependent on environment variables etc and harder to test).
`Buildkite::TestCollector::CI.env` itself is tested separately, so we still have coverage across the generated `run_env`.
I'm extracting this refactor from another change which will add tagging support, to make that other change smaller.
Related:
- https://github.com/buildkite/test-collector-ruby/pull/233

HTTPClient: `#post_upload` replaces `#post_json`; receives `run_env`

---

buildkite.yaml

Ruby 3.4 was released on Dec 2024. Time to build against it!

Add Ruby 3.4 to Buildkite build matrix

---

.buildkite/pipeline.release.yml
.buildkite/steps/release-gem
README.md

This adds a new pipeline.yml specifically for pushing gem releases to rubygems.org. We use the `rubygems-oidc` plugin to swap a Buildkite OIDC token for a temporary rubygems.org token that has permission to push this gem - that exchange process will only work from a special Buildkite pipeline that is triggered by a tag push to the repository.
I've updated the README with the new process. It's largely the same, except now any staff member with access to the release pipeline can approve the release. They no longer need to be added as an owner on [the gem](https://rubygems.org/gems/buildkite-test_collector), or need to have access to any shared credentials for our rubygems.org user.

Create new pipeline for releasing to rubygems

---

lib/buildkite/test_collector.rb
lib/buildkite/test_collector/http_client.rb
lib/buildkite/test_collector/uploader.rb
spec/test_collector/http_client_spec.rb
spec/test_collector/uploader_spec.rb

Allow `tags` to be specified for all executions uploaded by the collector; they will propagate onto all the test results (executions) within.
Arbitrary tags may not be supported yet; this is an upcoming/experimental feature. Reach out to Buildkite support for more information if you're interested.
Related:
- https://github.com/buildkite-plugins/test-collector-buildkite-plugin/pull/81
- Based on:
- #233
- #234

Buildkite::TestCollector.tags: specify tags for all executions

---

CHANGELOG.md
Gemfile.lock
lib/buildkite/test_collector/version.rb

Prepare for v2.8.0 release.
> * Buildkite::TestCollector.tags: specify tags for all executions by @pda in https://github.com/buildkite/test-collector-ruby/pull/235
> * Add Ruby 3.4 to Buildkite build matrix by @gchan in https://github.com/buildkite/test-collector-ruby/pull/236
> 
> **Full Changelog**: https://github.com/buildkite/test-collector-ruby/compare/v2.7.2...v2.8.0
Related:
- https://github.com/buildkite/test-collector-ruby/pull/237

Release v2.8.0

---

lib/buildkite/test_collector.rb
lib/buildkite/test_collector/library_hooks/rspec.rb
lib/buildkite/test_collector/minitest_plugin.rb
lib/buildkite/test_collector/minitest_plugin/trace.rb
lib/buildkite/test_collector/rspec_plugin/trace.rb
spec/test_collector/minitest_plugin/trace_spec.rb
spec/test_collector/rspec_plugin/trace_spec.rb

Draft support for per-execution tagging.
I don't love adding yet another `Thread.current[:_buildkite…]` fiber-local (global-ish) name, but I don't see a really good place to put these tags otherwise, and really it's an inconsequential implementation detail, compared to the public API in front of it. I don't think they really belong in `Buildkite::TestCollector::Tracer` (we're tagging the execution, not the potentially-nested traces therein) and adding them there just adds complexity.

`Buildkite::TestCollector.tag_execution(key, value)`

---

CHANGELOG.md
Gemfile.lock
lib/buildkite/test_collector/version.rb

Prepare for v2.9.0 release with per-execution tagging.
> ## v2.9.0
> 
> * `Buildkite::TestCollector.tag_execution(key, value)` by @pda in #240
> 
> **Full Changelog**: https://github.com/buildkite/test-collector-ruby/compare/v2.8.0...v2.9.0

Release v2.9.0
