buildkite/test-collector-ruby

- lib/rspec/buildkite/analytics/tracer.rb
https://api.rubyonrails.org/classes/ActiveSupport/HashWithIndifferentAccess.html
> Add the missing require to use Hash#indifferent_access

- Gemfile.lock
Whoops, meant to put this in PR #72
> Forgot to update gem

- Gemfile.lock
- lib/rspec/buildkite/analytics/version.rb
v0.6.2 picks up bugfix from #74
> Bump version + update

- Gemfile.lock
- lib/rspec/buildkite/analytics/version.rb
> Release 0.7.0

- .buildkite/pipeline
Add a block step to accept 3rd party contributions.
> Add a block step for forked Pull Requests

- CHANGELOG.md
- Gemfile.lock
- lib/rspec/buildkite/analytics/version.rb
> Bump version to v0.8.1

- lib/buildkite/collector/http_client.rb
- lib/buildkite/collector/uploader.rb
- spec/collector/minitest_plugin/reporter_spec.rb
This merges into #103.
This will make changes to HTTP easier in the future, also easier to mock in tests.
> Extract into a HTTP Client

- CHANGELOG.md
- Gemfile.lock
- lib/buildkite/test_collector/version.rb
This PR updates the gem version and changelog in preparation of releasing version 1.0.0.
> Prepare v1.0.0 release

- CHANGELOG.md
- Gemfile.lock
- lib/buildkite/test_collector/version.rb
> Bump version to v1.0.1

- Gemfile
- lib/buildkite/test_collector/session.rb
- lib/buildkite/test_collector/uploader.rb
There are still some leftover from the gem rename.
> Update rspec-buildkite-analytics with buildkite-test_collector

- CHANGELOG.md
- Gemfile.lock
- lib/buildkite/test_collector/version.rb
all changes https://github.com/buildkite/test-collector-ruby/compare/v1.0.1...main
> Release v1.1.0

- CHANGELOG.md
- Gemfile.lock
- lib/buildkite/test_collector/version.rb
all changes: https://github.com/buildkite/test-collector-ruby/compare/v1.1.0...main
> Release v1.1.1

- CODE_OF_CONDUCT.md
> Update Code of Conduct contract email address

- CHANGELOG.md
- lib/buildkite/test_collector/version.rb
PIE-1004
[1.1.2..version-1.1.3](https://github.com/buildkite/test-collector-ruby/compare/v1.1.2..version-1.1.3)
> Version 1.1.3

- README.md
There is a corresponding PR on the docs repo: https://github.com/buildkite/docs/pull/1738
> Document the annotation method

- CHANGELOG.md
- Gemfile.lock
- lib/buildkite/test_collector/version.rb
> Release v1.3.0

- CHANGELOG.md
- Gemfile.lock
- lib/buildkite/test_collector/version.rb
Bump patch version up to release the following fix #165
> Release 1.3.1

- CHANGELOG.md
- Gemfile.lock
- lib/buildkite/test_collector/version.rb
Bump minor version of gem to release #167
> Bump minor version

- CHANGELOG.md
- Gemfile.lock
- lib/buildkite/test_collector/version.rb
PIE-1387
Diff:
https://github.com/buildkite/test-collector-ruby/compare/v1.4.2...c40d00070c84d5fd50b561a23669855f72fa0c08
> Bump version to 1.5.0

- CHANGELOG.md
- Gemfile.lock
- lib/buildkite/test_collector/version.rb
- spec/test_collector/http_client_spec.rb
> Create pre-release for 2.1.0

- CHANGELOG.md
- Gemfile.lock
- README.md
- lib/buildkite/test_collector/version.rb
- spec/test_collector/http_client_spec.rb
Bumping the version so we can release v2.1 of the gem ✨
> Release v2.1

- CHANGELOG.md
- Gemfile.lock
- lib/buildkite/test_collector/version.rb
- spec/test_collector/http_client_spec.rb
Release gem with new gzipping of upload api payload #183
> release v2.2.0

- CHANGELOG.md
- Gemfile.lock
- lib/buildkite/test_collector/version.rb
> Update version v2.3

- lib/buildkite/test_collector/ci.rb
- spec/test_collector/ci_spec.rb
- spec/test_collector/http_client_spec.rb
To gather insights on Ruby version usage. 
PIE-1968
> Report Ruby version to Test Analytics

- CHANGELOG.md
- Gemfile.lock
- lib/buildkite/test_collector/version.rb
Prepare v2.6.0 release for #215
> - Trace spans can be filtered by minimum duration
> Prepare v2.6.0 release

- lib/buildkite/test_collector/library_hooks/rspec.rb
[Skipping my journey of discovering this because this is a public repo....]
Rspec's  `around` hook has some undocumented behavoir, look at this example:
```ruby
RSpec.configure do |config|
config.around(:each) do |example|
puts "Outer around hook start"
begin
example.run
ensure
puts "Outer around hook end"
end
end
end
RSpec.configure do |config|
config.around(:each) do |example|
puts "Inner around hook start"
raise "Error in inner hook"
example.run
puts "Inner around hook end"
end
end
RSpec.describe "Example" do
it "does something" do
expect(true).to be true
end
end
```
If we don't use `ensure` then neither "Inner around hook end" and "Outer around hook end" gets executed. 
---
In another word, prior to this fix, any Rspec test fails that's caused by `around` hook failure will be missed.
> Fix missing failed examples if rspec hooks fail

- CHANGELOG.md
- Gemfile.lock
- lib/buildkite/test_collector/version.rb
`$ git log --oneline --no-merges --no-decorate v2.7.0...v2.7.1`
b9ca522 v2.7.1
50a8ba0 Remove failed test links from the job log
2d3796e Update CODEOWNERS
ffec089 Update test analytics references to test engine
> Release v2.7.1

- README.md
Per our agreement, we aims to be rich doc, light readme. 
This PR removes some dead docs from README and add pointer to our official doc.
> Update README, promoting doc site

- .rspec
- buildkite.yaml
Our CI has been pretty unreliable recently. This PR fixes that. 
This is also serving as an example to how this is done.
Credits to @lucaswilric for working out the IAM puzzle! 
Completes PIE-3345
> PIE-3345: fix ECR rate limit problem on CI
